### ISSUE TITLE
How to add more Formula templates on second row?

### ISSUE THREAD

**Issue by purnomosejati** [c-w/mathquill4quill#45]
Hi Sir, 

This mathquil4quil is great.

I need to add more fomula on template and show it as column & row.

The existing feature is only showing single row formula.

Please let me know if it is possible

**Comment by c-w** [comment]
Since version [2.0.0](https://github.com/c-w/mathquill4quill/releases/tag/v2.0.0) it's possible to override the styles used by mathquill4quill with your own custom CSS. Wrapping the operator buttons on multiple columns can be achieved by setting the [flex-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-wrap) property on the operator button container.

Required custom CSS:

```css
.mathquill4quill-operator-container {
  flex-wrap: wrap;
}
```

Resulting UI:

![Screenshot showing multiple rows of operator buttons](https://user-images.githubusercontent.com/1086421/77368592-eff7ac80-6d32-11ea-9bd0-1785cb7471fb.png)

Let me know if this addresses your use-case!

**Comment by c-w** [comment]
In an effort to make mathquill4quill more responsive, wrapping operator buttons onto multiple rows has been made the default in [v2.1.2](https://github.com/c-w/mathquill4quill/releases/tag/v2.1.2).
