### ISSUE TITLE
Doesn't work with React 17

### ISSUE THREAD

**Issue by pramod2** [c-w/mathquill4quill#81]
I'm making a NextJS application that needs math formula editing support, and this module looks like exactly what I need. However, npm install doesn't work because react-quill is using older version of React and there are errors resolving dependency tree. Is there any fix or workaround for this without going back to old React version?

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nextjs@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.9 || ^15.3.0 || ^16.0.0" from react-quill@1.3.5
npm ERR! node_modules/react-quill
npm ERR!   react-quill@"^1.3.5" from the root project

**Comment by c-w** [comment]
`mathquill4quill` has no explicitly listed dependencies. It looks to me like this error comes from `react-quill` which at v1.3.5 only supports React v16 ([see code](https://github.com/zenoamaro/react-quill/blob/301dee7ef2bbe93575f809ce5aab5451009b4874/package.json#L56)). It looks like this is fixed in their mainline and will be published as v2.0.0.-beta4 ([see code](https://github.com/zenoamaro/react-quill/blob/2efde23c12d296fd9aefc825d6463448b51efc49/package.json#L51)). So you can either wait until the next release of `react-quill` or install the dependency from the latest mainline git branch.
